name: Challenge
description: Challenge describe
title: "Challenge: "
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Enter your email in case I need to contact you for more information
      placeholder: email@example.com
    validations:
      required: true
  - type: textarea
    id: describe-challenge
    attributes:
      label: Challenge Description
      description: A clear and concise description of the challenge
      placeholder: "Type here"
    validations:
      required: true
  - type: textarea
    id: additional-tips
    attributes:
      label: "Additional tips"
      placeholder: "Type here"
    validations:
      required: true
